[package]
name = "reerror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
wgpu = "0.13"

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.17"
